name: Spell Checker
on: [pull_request, push]
jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@master
        with:
          path: ./Document
          ignore_words_list: OWASP,MASVS,MASTG
